<?php

namespace Aws\SecurityHub;

use Aws\AwsClient;
use Aws\Result;
use GuzzleHttp\Promise\Promise;

/**
 * This client is used to interact with the **AWS SecurityHub** service.
 * @method Result acceptInvitation( array $args = [] )
 * @method Promise acceptInvitationAsync( array $args = [] )
 * @method Result batchDisableStandards( array $args = [] )
 * @method Promise batchDisableStandardsAsync( array $args = [] )
 * @method Result batchEnableStandards( array $args = [] )
 * @method Promise batchEnableStandardsAsync( array $args = [] )
 * @method Result batchImportFindings( array $args = [] )
 * @method Promise batchImportFindingsAsync( array $args = [] )
 * @method Result createActionTarget( array $args = [] )
 * @method Promise createActionTargetAsync( array $args = [] )
 * @method Result createInsight( array $args = [] )
 * @method Promise createInsightAsync( array $args = [] )
 * @method Result createMembers( array $args = [] )
 * @method Promise createMembersAsync( array $args = [] )
 * @method Result declineInvitations( array $args = [] )
 * @method Promise declineInvitationsAsync( array $args = [] )
 * @method Result deleteActionTarget( array $args = [] )
 * @method Promise deleteActionTargetAsync( array $args = [] )
 * @method Result deleteInsight( array $args = [] )
 * @method Promise deleteInsightAsync( array $args = [] )
 * @method Result deleteInvitations( array $args = [] )
 * @method Promise deleteInvitationsAsync( array $args = [] )
 * @method Result deleteMembers( array $args = [] )
 * @method Promise deleteMembersAsync( array $args = [] )
 * @method Result describeActionTargets( array $args = [] )
 * @method Promise describeActionTargetsAsync( array $args = [] )
 * @method Result describeHub( array $args = [] )
 * @method Promise describeHubAsync( array $args = [] )
 * @method Result describeProducts( array $args = [] )
 * @method Promise describeProductsAsync( array $args = [] )
 * @method Result disableImportFindingsForProduct( array $args = [] )
 * @method Promise disableImportFindingsForProductAsync( array $args = [] )
 * @method Result disableSecurityHub( array $args = [] )
 * @method Promise disableSecurityHubAsync( array $args = [] )
 * @method Result disassociateFromMasterAccount( array $args = [] )
 * @method Promise disassociateFromMasterAccountAsync( array $args = [] )
 * @method Result disassociateMembers( array $args = [] )
 * @method Promise disassociateMembersAsync( array $args = [] )
 * @method Result enableImportFindingsForProduct( array $args = [] )
 * @method Promise enableImportFindingsForProductAsync( array $args = [] )
 * @method Result enableSecurityHub( array $args = [] )
 * @method Promise enableSecurityHubAsync( array $args = [] )
 * @method Result getEnabledStandards( array $args = [] )
 * @method Promise getEnabledStandardsAsync( array $args = [] )
 * @method Result getFindings( array $args = [] )
 * @method Promise getFindingsAsync( array $args = [] )
 * @method Result getInsightResults( array $args = [] )
 * @method Promise getInsightResultsAsync( array $args = [] )
 * @method Result getInsights( array $args = [] )
 * @method Promise getInsightsAsync( array $args = [] )
 * @method Result getInvitationsCount( array $args = [] )
 * @method Promise getInvitationsCountAsync( array $args = [] )
 * @method Result getMasterAccount( array $args = [] )
 * @method Promise getMasterAccountAsync( array $args = [] )
 * @method Result getMembers( array $args = [] )
 * @method Promise getMembersAsync( array $args = [] )
 * @method Result inviteMembers( array $args = [] )
 * @method Promise inviteMembersAsync( array $args = [] )
 * @method Result listEnabledProductsForImport( array $args = [] )
 * @method Promise listEnabledProductsForImportAsync( array $args = [] )
 * @method Result listInvitations( array $args = [] )
 * @method Promise listInvitationsAsync( array $args = [] )
 * @method Result listMembers( array $args = [] )
 * @method Promise listMembersAsync( array $args = [] )
 * @method Result listTagsForResource( array $args = [] )
 * @method Promise listTagsForResourceAsync( array $args = [] )
 * @method Result tagResource( array $args = [] )
 * @method Promise tagResourceAsync( array $args = [] )
 * @method Result untagResource( array $args = [] )
 * @method Promise untagResourceAsync( array $args = [] )
 * @method Result updateActionTarget( array $args = [] )
 * @method Promise updateActionTargetAsync( array $args = [] )
 * @method Result updateFindings( array $args = [] )
 * @method Promise updateFindingsAsync( array $args = [] )
 * @method Result updateInsight( array $args = [] )
 * @method Promise updateInsightAsync( array $args = [] )
 */
class SecurityHubClient extends AwsClient {
}
