<?php

namespace Aws\Backup;

use Aws\AwsClient;
use Aws\Result;
use GuzzleHttp\Promise\Promise;

/**
 * This client is used to interact with the **AWS Backup** service.
 * @method Result createBackupPlan( array $args = [] )
 * @method Promise createBackupPlanAsync( array $args = [] )
 * @method Result createBackupSelection( array $args = [] )
 * @method Promise createBackupSelectionAsync( array $args = [] )
 * @method Result createBackupVault( array $args = [] )
 * @method Promise createBackupVaultAsync( array $args = [] )
 * @method Result deleteBackupPlan( array $args = [] )
 * @method Promise deleteBackupPlanAsync( array $args = [] )
 * @method Result deleteBackupSelection( array $args = [] )
 * @method Promise deleteBackupSelectionAsync( array $args = [] )
 * @method Result deleteBackupVault( array $args = [] )
 * @method Promise deleteBackupVaultAsync( array $args = [] )
 * @method Result deleteBackupVaultAccessPolicy( array $args = [] )
 * @method Promise deleteBackupVaultAccessPolicyAsync( array $args = [] )
 * @method Result deleteBackupVaultNotifications( array $args = [] )
 * @method Promise deleteBackupVaultNotificationsAsync( array $args = [] )
 * @method Result deleteRecoveryPoint( array $args = [] )
 * @method Promise deleteRecoveryPointAsync( array $args = [] )
 * @method Result describeBackupJob( array $args = [] )
 * @method Promise describeBackupJobAsync( array $args = [] )
 * @method Result describeBackupVault( array $args = [] )
 * @method Promise describeBackupVaultAsync( array $args = [] )
 * @method Result describeProtectedResource( array $args = [] )
 * @method Promise describeProtectedResourceAsync( array $args = [] )
 * @method Result describeRecoveryPoint( array $args = [] )
 * @method Promise describeRecoveryPointAsync( array $args = [] )
 * @method Result describeRestoreJob( array $args = [] )
 * @method Promise describeRestoreJobAsync( array $args = [] )
 * @method Result exportBackupPlanTemplate( array $args = [] )
 * @method Promise exportBackupPlanTemplateAsync( array $args = [] )
 * @method Result getBackupPlan( array $args = [] )
 * @method Promise getBackupPlanAsync( array $args = [] )
 * @method Result getBackupPlanFromJSON( array $args = [] )
 * @method Promise getBackupPlanFromJSONAsync( array $args = [] )
 * @method Result getBackupPlanFromTemplate( array $args = [] )
 * @method Promise getBackupPlanFromTemplateAsync( array $args = [] )
 * @method Result getBackupSelection( array $args = [] )
 * @method Promise getBackupSelectionAsync( array $args = [] )
 * @method Result getBackupVaultAccessPolicy( array $args = [] )
 * @method Promise getBackupVaultAccessPolicyAsync( array $args = [] )
 * @method Result getBackupVaultNotifications( array $args = [] )
 * @method Promise getBackupVaultNotificationsAsync( array $args = [] )
 * @method Result getRecoveryPointRestoreMetadata( array $args = [] )
 * @method Promise getRecoveryPointRestoreMetadataAsync( array $args = [] )
 * @method Result getSupportedResourceTypes( array $args = [] )
 * @method Promise getSupportedResourceTypesAsync( array $args = [] )
 * @method Result listBackupJobs( array $args = [] )
 * @method Promise listBackupJobsAsync( array $args = [] )
 * @method Result listBackupPlanTemplates( array $args = [] )
 * @method Promise listBackupPlanTemplatesAsync( array $args = [] )
 * @method Result listBackupPlanVersions( array $args = [] )
 * @method Promise listBackupPlanVersionsAsync( array $args = [] )
 * @method Result listBackupPlans( array $args = [] )
 * @method Promise listBackupPlansAsync( array $args = [] )
 * @method Result listBackupSelections( array $args = [] )
 * @method Promise listBackupSelectionsAsync( array $args = [] )
 * @method Result listBackupVaults( array $args = [] )
 * @method Promise listBackupVaultsAsync( array $args = [] )
 * @method Result listProtectedResources( array $args = [] )
 * @method Promise listProtectedResourcesAsync( array $args = [] )
 * @method Result listRecoveryPointsByBackupVault( array $args = [] )
 * @method Promise listRecoveryPointsByBackupVaultAsync( array $args = [] )
 * @method Result listRecoveryPointsByResource( array $args = [] )
 * @method Promise listRecoveryPointsByResourceAsync( array $args = [] )
 * @method Result listRestoreJobs( array $args = [] )
 * @method Promise listRestoreJobsAsync( array $args = [] )
 * @method Result listTags( array $args = [] )
 * @method Promise listTagsAsync( array $args = [] )
 * @method Result putBackupVaultAccessPolicy( array $args = [] )
 * @method Promise putBackupVaultAccessPolicyAsync( array $args = [] )
 * @method Result putBackupVaultNotifications( array $args = [] )
 * @method Promise putBackupVaultNotificationsAsync( array $args = [] )
 * @method Result startBackupJob( array $args = [] )
 * @method Promise startBackupJobAsync( array $args = [] )
 * @method Result startRestoreJob( array $args = [] )
 * @method Promise startRestoreJobAsync( array $args = [] )
 * @method Result stopBackupJob( array $args = [] )
 * @method Promise stopBackupJobAsync( array $args = [] )
 * @method Result tagResource( array $args = [] )
 * @method Promise tagResourceAsync( array $args = [] )
 * @method Result untagResource( array $args = [] )
 * @method Promise untagResourceAsync( array $args = [] )
 * @method Result updateBackupPlan( array $args = [] )
 * @method Promise updateBackupPlanAsync( array $args = [] )
 * @method Result updateRecoveryPointLifecycle( array $args = [] )
 * @method Promise updateRecoveryPointLifecycleAsync( array $args = [] )
 */
class BackupClient extends AwsClient {
}
